### ISSUE TITLE
Switch from JCenter to Maven Central for builds

### ISSUE THREAD

**Issue by msfjarvis** [zeapo/Android-Password-Store#1301]
JCenter is shutting down on [May 1st 2021](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/)﻿ so we're going to need to make a plan to switch.

As a test I did a quick `sed -i 's/jcenter/mavenCentral/g` in our Gradle build files and it seems we only have three dependencies to get fixed.

- [x] AndroidFastScroll (Filed https://github.com/zhanghai/AndroidFastScroll/issues/35)
- [x] ModernAndroidPreferences (~~Contacted author privately~~ [Published](https://repo.maven.apache.org/maven2/de/maxr1998/modernandroidpreferences/2.0/))
- [x] OpenKeychain sshauthentication-api (~~Prayed to the moon god for mercy~~ Saw that the repository was alive again, so filed an issue https://github.com/open-keychain/open-keychain/issues/2645)

And for our own libraries

- [x] Reserve the `com.github.android-password-store` Group ID (Filed a ticket to their [JIRA](https://issues.sonatype.org/browse/OSSRH-64039))
- [x] Adapt Gradle setup for publishing to Maven Central
- [x] Adapt CI for publishing to Maven Central
- [x] Publish current versions to Maven Central (Published at https://repo1.maven.org/maven2/com/github/android-password-store/)
- [x] ~~Setup snapshot deployment for libraries (?)~~ We don't change the libraries frequently enough to warrant this

**Comment by msfjarvis** [comment]
@fmeum can we migrate away from our current fastscroll library to something that does have artefacts on Maven Central? The author hasn't replied in nearly a month since I filed the issue.

**Comment by fmeum** [comment]
Do you know other libraries that would do this for us? I just found https://github.com/reddit/IndicatorFastScroll.

We don't really have any special requirements apart from having this work with multi-selection.

**Comment by msfjarvis** [comment]
> Do you know other libraries that would do this for us? I just found [reddit/IndicatorFastScroll](https://github.com/reddit/IndicatorFastScroll).

https://github.com/timusus/RecyclerView-FastScroll and https://github.com/quiph/RecyclerView-FastScroller seem like decent options as well.
> 
> We don't really have any special requirements apart from having this work with multi-selection.

We've had issues with `recyclerview-selection`'s interaction with AndroidFastScroll too, and I think I saw a comment about replacing it with tracking a `Set<PasswordItem>` instead. If none of the libraries play well with `recyclerview-selection` then a refactor can be considered to ease the transition.

Ideally we'd want to avoid all of this, so I'm going to send an email to the developer and hope that catches their eye.

**Comment by msfjarvis** [comment]
The author of the fastscroll library doesn't seem to be very active but there's not much we can do about it right now, so I'm going to go ahead and close this issue. If nothing has changed when JCenter is actually planning to shut down sometime next year, we'll consider migration.
