### ISSUE TITLE
Tracking issue for enabling Gradle configuration cache

### ISSUE THREAD

**Issue by msfjarvis** [zeapo/Android-Password-Store#1708]
Gradle introduced [Configuration Cache](https://docs.gradle.org/current/userguide/configuration_cache.html) as a feature that caches the output of the configuration phase of Gradle builds, before any actual tasks are run, to enable instant task execution. This is the tracking issue to implement full support for it in Password Store, ultimately making it the default, to improve developer experience. Known problems as of now are documented below, more will be added over time until configuration cache has been enabled on the develop branch.

## Known issues
- [x] Versioning Plugin is incompatible with configuration caching (#1709)
- [x] PublicSuffixList Plugin is incompatible with configuration caching (#1709)
- [x] Crowdin Plugin is incompatible with configuration caching (Plans to make it compatible with configuration caching are abandoned, just use it with `--no-configuration-cache`)
- [x] AGP's `PerModuleReportDependenciesTask ` task is incompatible with configuration caching (being tracked [here](https://issuetracker.google.com/issues/162074215)) (#1711)
- [x] ~~`build-logic` subprojects occasionally fail to generate script accessors~~ Tends to only happen in CI, where configuration cache will not be enabled.
- [x] `kotlinx-kover` is incompatible with configuration caching (#1709)
